// DARK MODE
export const DARK_MODE_SUCCESS = 'DARK_MODE_SUCCESS';
export const DARK_MODE_FAIL = 'DARK_MODE_FAIL';
export const GET_DARK_MODE = 'GET_DARK_MODE';

// USER
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';

// banner 
export const BANNER_REQUEST = 'BANNER_REQUEST';
export const BANNER_GET_SUCCESS = 'BANNER_GET_SUCCESS';
export const BANNER_FAIL = 'BANNER_FAIL';

// recently viewed
export const RECENTLY_VIEWED_REQUEST = 'RECENTLY_VIEWED_REQUEST';
export const RECENTLY_VIEWED_GET_SUCCESS = 'RECENTLY_VIEWED_GET_SUCCESS';
export const RECENTLY_VIEWED_CREATE_SUCCESS = 'RECENTLY_VIEWED_CREATE_SUCCESS';
export const RECENTLY_VIEWED_FAIL = 'RECENTLY_VIEWED_FAIL';

// product
export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';

// search api
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

// CART
export const CART_REQUEST = 'CART_REQUEST';
export const GET_USER_CART_ITEM = 'GET_USER_CART_ITEM';
export const CART_FAIL = 'CART_FAIL';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';


// WISHLIST
export const WISHLIST_REQUEST = 'WISHLIST_REQUEST';
export const GET_USER_WISHLIST_ITEM = 'GET_USER_WISHLIST_ITEM';
export const WISHLIST_FAIL = 'WISHLIST_FAIL';
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS';
export const REMOVE_FROM_WISHLIST_SUCCESS = 'REMOVE_FROM_WISHLIST_SUCCESS';


// Address
export const ADDRESS_REQUEST = 'ADDRESS_REQUEST';
export const GET_USER_ADDRESS_SUCCESS = 'GET_USER_ADDRESS_SUCCESS';
export const ADDRESS_FAIL = 'ADDRESS_FAIL';
export const ADD_USER_ADDRESS_SUCCESS = 'ADD_USER_ADDRESS_SUCCESS';
export const UPDATE_USER_ADDRESS_SUCCESS = 'UPDATE_USER_ADDRESS_SUCCESS';
export const DELETE_USER_ADDRESS_SUCCESS = 'DELETE_USER_ADDRESS_SUCCESS';
export const SET_DEFAULT_ADDRESS_SUCCESS = 'SET_DEFAULT_ADDRESS_SUCCESS';

// Order
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const GET_USER_ORDER_SUCCESS = 'GET_USER_ORDER_SUCCESS';
export const ORDER_FAIL = 'ORDER_FAIL';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';